### ISSUE TITLE
unable to select aws credentials from drop down

### ISSUE THREAD

**Issue by lifeofguenter** [jenkinsci/aws-sqs-plugin#14]
This was obviously going to fail ;)

With the latest release (2.0) I am unable to select aws credentials from the drop down, even though they exist:

<img width="422" alt="screen shot 2017-12-13 at 11 26 25" src="https://user-images.githubusercontent.com/241073/33931444-a7e6f6d6-dff8-11e7-8ae9-807e2be9a262.png">

I only see "slack-token" which is not an aws credential.

The `aws-credentials` plugin is installed.

**Comment by mvk** [comment]
thank you, @lifeofguenter, I don't know why it is "of course". will going to fix it.

**Comment by alitet01** [comment]
Hello, @lifeofguenter,
Amazon SQS queue use text security credentials pair Access key ID and Access key secret.
Jenkins credentials store has a few kinds of credentials. You have to put AWS SQS credentials pair into Secret text kind of Jenkins credentials store object, Access key ID as ID and Access key secret as Secret.
AWS-SQS-plugin use plain text credentials and only this kind of credentials objects are visible for the plugin.
Note that the Credentials drop down list will show You the Description You wrote to Jenkins credentials store object,

**Comment by lifeofguenter** [comment]
thanks @alitet01 - that `README.md` update was dearly needed!
