### ISSUE TITLE
Jenkinsfile - SQSTriggerQueue

### ISSUE THREAD

**Issue by rjackson-dev-ops** [jenkinsci/aws-sqs-plugin#18]
Folks,

Is it possible to use your plugin in the triggers section of a Jenkinsfile?

Regards,

Robert

**Comment by rjackson-dev-ops** [comment]
Here is the syntax my team figured out for using this great plugin in either a job DSL or scripted pipeline.

Job DSL SQS Trigger:

 job ("ev-${jobName}") {
      if (jobName.contains("sqs-trigger")) {
        triggers {
          sqsTrigger {
            queueUuid(sqsQueueUuid)
          }
        }

Jenkins File using scripted pipeline with SQS Trigger:

def sqsQueueUuid = 'ExampleQueue'
properties([pipelineTriggers([
  [$class: "SQSTrigger", queueUuid: sqsQueueUuid]
  ])
])
node {

  try {
    stage('Trigger') {
      steps : {
        checkout scm
        print params.sqs_body
      }
    }
  }

  Additionally for the scripted Jenkins file, we had to build the job first to get it to setup the queue.

**Comment by tonyallain** [comment]
How did you determine the Uuid of the queue?

**Comment by rjackson-dev-ops** [comment]
Using this queue name to send from Jenkins 1.

# In Ruby rake task
queue_name = 'MY-APP_SQS_QUEUE.fifo'
queue_url = sqs_client.get_queue_url(queue_name: queue_name).queue_url
..........
sqs_client.send_message(
      queue_url: queue_url,
      message_body: JSON[message_body],
      message_group_id: 'ProdTrigger'
    )

Then to receive this message on Jenkins 2, we put this the DSL for the Jenkinsfile.

triggers {
    sqsTrigger {
      queueUuid(MY-APP_SQS_QUEUE')
    }
