### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by DevilWAH** [jenkinsci/aws-sqs-plugin#5]
IS this just a trigger or can i access the info in the SQS queue as input to my build project? 

I want to pull the InstanceID from the SQS message run a script to find out some info such as IP address and used these are variable with in the build process. but I can't see how to do this? 

Thank you

**Comment by lifeofguenter** [comment]
+1 - I was hoping that the payload would be inserted as environment variable? Then any underlaying script can do further processing?

**Comment by mvk** [comment]
@lifeofguenter thanks, closing this one.
